### PR TITLE
Fix "U_" prefix also to layer name definitions

### PR DESCRIPTION
**Pull request by UncleCJ**
This is 756578518e9 - I am not sure, but have searched the code and believe this may be what is needed to make builds work out of the box again

### CODE REVIEW

**Comment by manna-harbour** [comment]
Thanks for catching the mistake! I forgot to update the layer names in the `defsrc` when adding the `U_` prefix.

The fix is to change `LAYER` to `U_##LAYER` here https://github.com/manna-harbour/miryoku_kmonad/blob/756578518e98c9c205363d1d80bb957d1d6ee411/src/miryoku_kmonad.kbd.cpp#L54 (and regenerate the default `miryoku_kmonad/src/build/miryoku_kmonad.kbd`).

**Comment by UncleCJ** [comment]
That's so cool! Just dipping my toes here, relying on the GitHub Workflow and don't have working build env, would be happy if you could apply the fix yourself?
I'd love to provide a translation, but this is where I'm at :-) https://twitter.com/unclecj/status/1544414980019208198

Oh, another issue, not sure about if there's even any appropriate intended behavior, but for `alphas=QWERTY`, TAP layer still become colemak?

    (deflayer TAP
    	q w f p b j l u y '
    	a r s t g m n e i o
    	z x c d v k h , . /
    	esc spc tab ent bspc del
    	;
    )

**Comment by manna-harbour** [comment]
Actually, since you've already manually made the correct changes in the generated file, you don't really need to regenerate. If you're interested, you can just add the other change I mentioned to your branch and I'll merge it after checking. You can also use the workflow to produce the generated file after making the change (but it should be identical to what you have already). But if not that's fine too, I can just make the change myself.

**Comment by manna-harbour** [comment]
Yes, for Tap see https://github.com/manna-harbour/miryoku/tree/master/docs/reference#additional-features. It would make sense for Tap to default to the same alpha arrangement as Base. That's currently not easy to implement, but I'll try to do that later after making some other implementation changes. For now you need to select the alpha arrangement for Tap separately, see https://github.com/manna-harbour/miryoku/tree/master/docs/reference#tap. You can use the custom rules field in the workflow.

**Comment by manna-harbour** [comment]
Added in https://github.com/manna-harbour/miryoku_kmonad/commit/396de5be28f9608fbabcadb0ad4bf6d9c4d3ec91.  Thanks again!

Also added a dry run to the test workflow to check for a bad generated .kbd file: https://github.com/manna-harbour/miryoku_kmonad/commit/f5dbfe74f0eebe05f9655c5415fdf17ab3fb057f.

**Comment by UncleCJ** [comment]
Beautiful! As I said, I barely am sufficiently familiar with this and I don't have the full Haskell + CPP environment under Windows. My day job consists of plenty making sure that peculiar build pipelines are reliable, there's a real point in the developers "owning" it.
With that said, you've created a really impressive thing here and I'm looking forward to exploring it! Of course you also get a gold star for responsiveness. See you around!

**Pull request closed without merging**
